### PR TITLE
controller: Stop panicking when unable to create pod.

### LINKED ISSUE #525: Controller crashing when akri config is bad
What I have experienced:

I deployed a bad akri configuration which made my akri controller crash. I don't believe this should happen:

Akri config (obviously broken):
```
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-adb
spec:
  discoveryHandler:
    name: usb
    discoveryDetails: |+
      class: 0xff
      subClass: 0x42
      protocol: 0x1
  brokerSpec:
    brokerPodSpec:
      setHostnameAsFQDN: true
      containers:
      - name: akri-adb-broker
        image: v4l:latest
        securityContext:
          privileged: true
        resources:
          requests:
            "{{' }}PLACEHOLDER{{ '}}' }}" : "1"
            memory: 10Mi
            cpu: 10m
          limits:
            "{{ '{{' }}PLACEHOLDER{{ '}}' }}" : "1"
            memory: 30Mi
            cpu: 29m
  instanceServiceSpec:
    type: ClusterIP
    ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 8083
  configurationServiceSpec:
    type: ClusterIP
    ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 8083
  brokerProperties: {}
  capacity: 1
```

this led to the following logs:
```
[2022-09-30T09:42:15Z TRACE akri_shared::k8s::pod] create_pod enter
[2022-09-30T09:42:15Z INFO  akri_shared::k8s::pod] create_pod pods.create(...).await?:
[2022-09-30T09:42:15Z ERROR akri_shared::k8s::pod] create_pod pods.create [Ok("{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"labels\":{\"akri.sh/configuration\":\"akri-adb\",\"akri.sh/instance\":\"akri-adb-4e943c\",\"akri.sh/target-node\":\"k3d-nucdev-server-0\",\"app\":\"akri-adb-4e943c-pod\",\"controller\":\"akri.sh\"},\"name\":\"akri-adb-4e943c-pod\",\"namespace\":\"rdc\",\"ownerReferences\":[{\"apiVersion\":\"akri.sh/v0\",\"blockOwnerDeletion\":true,\"controller\":true,\"kind\":\"Instance\",\"name\":\"akri-adb-4e943c\",\"uid\":\"a74a8e30-9c36-4a11-a5a0-0c4b5fe47c5f\"}]},\"spec\":{\"affinity\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchFields\":[{\"key\":\"metadata.name\",\"operator\":\"In\",\"values\":[\"k3d-nucdev-server-0\"]}]}]}}},\"containers\":[{\"image\":\"quay.io/saucelabs/v4l:713aa3bc\",\"name\":\"akri-adb-broker\",\"resources\":{\"limits\":{\"cpu\":\"29m\",\"memory\":\"30Mi\",\"{{ '{{' }}PLACEHOLDER{{ '}}' }}\":\"1\"},\"requests\":{\"cpu\":\"10m\",\"memory\":\"10Mi\",\"{{ '{{' }}PLACEHOLDER{{ '}}' }}\":\"1\"}},\"securityContext\":{\"privileged\":true}}]}}")] returned kube error: ErrorResponse { status: "Failure", message: "Pod \"akri-adb-4e943c-pod\" is invalid: [spec.containers[0].resources.limits[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: \"{{ '{{' }}PLACEHOLDER{{ '}}' }}\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.containers[0].resources.limits[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: \"{{ '{{' }}PLACEHOLDER{{ '}}' }}\": must be a standard resource for containers, spec.containers[0].resources.requests[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: \"{{ '{{' }}PLACEHOLDER{{ '}}' }}\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.containers[0].resources.requests[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: \"{{ '{{' }}PLACEHOLDER{{ '}}' }}\": must be a standard resource for containers]", reason: "Invalid", code: 422 }
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Pod "akri-adb-4e943c-pod" is invalid: [spec.containers[0].resources.limits[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: "{{ '{{' }}PLACEHOLDER{{ '}}' }}": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.containers[0].resources.limits[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: "{{ '{{' }}PLACEHOLDER{{ '}}' }}": must be a standard resource for containers, spec.containers[0].resources.requests[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: "{{ '{{' }}PLACEHOLDER{{ '}}' }}": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.containers[0].resources.requests[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: "{{ '{{' }}PLACEHOLDER{{ '}}' }}": must be a standard resource for containers]: Invalid', controller/src/util/instance_action.rs:82:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', controller/src/main.rs:48:64
Error: JoinError::Panic(...)
```
I believe the following unwrap is the culprit here:
https://github.com/project-akri/akri/blob/befa9435f15b84391d104668c450d8ec0a545493/controller/src/main.rs#L48

### PR DESCRIPTION
**Pull request by diconico07**
**What this PR does / why we need it**:
Currently the controller panic if it encounters an error while trying to create a pod/job for an instance, thus causing an impact far wider than just the failing instance.

This should only have impact on the said instance, so as a first step, this commit stop the controller from panicking in this case and just output a log entry.

This fixes #525 

**Special notes for your reviewer**:
This is a first step toward better user error handling the next steps could be:
 - Identify if there are errors that should still make the controller panic
 - Generate a kubernetes event indicating failure to create broker
 - Add a status field to Instance (and Configuration ?), so Akri can  send feedback to the user this way. This item would need a proposal  and further discussion.

**If applicable**:
- [ ] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [x] this PR contains unit tests
- [x] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [x] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [x] inline documentation builds (`cargo doc`)
- [x] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

File: controller/src/util/instance_action.rs [hunk 1]
```diff
@@ -419,20 +419,27 @@ pub async fn handle_instance_change(
...
+                    instance,
                     *configuration.metadata.generation.as_ref().unwrap(),
                     j,
                     action,
                     kube_interface,
                 )
                 .await
             }
+        };
+        match instance_change_result {
```
Comment (bfjelds) [inline controller/src/util/instance_action.rs:437]: i wonder if this can be simplified (forgive my terrible rust memory):

```rust
    if let Some(broker_spec) = &configuration.spec.broker_spec {
        match broker_spec {
        let instance_change_result = match broker_spec {
            . . .
        };
        if let Err(e) = match instance_change_result {
            error!("Unable to handle Broker action: {:?}", e);
        }
    } 
    Ok(())
}
```

Comment (diconico07) [reply controller/src/util/instance_action.rs]: Indeed, way easier to read now, thanks for pointing it.

Comment (bfjelds) [reply controller/src/util/instance_action.rs]: lol ... might even be able to combine the `let instnace_change_result` block with the `if let Err(e)` block.  :)

**Review by bfjelds — APPROVED** [review]
