### PR TITLE
agent: Fix a stop discovery channel issue

### LINKED ISSUE #601: Changing a `Configuration` freezes the other ones for that discovery handler
**Describe the bug**
With multiple `Configuration` for a given discovery handler (only tested udev one, but as the issue is in the agent, they all should be affected), a change to one of the `Configuration` "freezes" the other ones, they won't get any new device nor delete old ones.

**To Reproduce**
1. With akri installed with udev discovery handler activated
2. Create 2 `Configuration` items matching for removable devices
3. Ensure device instances appears
4. Modify or delete one of the `Configuration`
5. Unplug one of devices matching the other `Configuration`
6. Nothing happens (instance is not deleted)

**Logs (please share snips of applicable logs)**
```
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z TRACE agent::util::config_action] handle_config - something happened to a configuration
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z INFO  agent::util::config_action] handle_config - added or modified Configuration "udev-keyboard"
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z INFO  agent::util::config_action] handle_config - modified Configuration Some("udev-keyboard")
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z TRACE agent::util::config_action] handle_config_delete - for config ("akri-discovered", "udev-keyboard") telling do_periodic_discovery to end
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z TRACE agent::util::discovery_operator::start_discovery] start_discovery - received message to stop checking connectivity status for configuration udev-keyboard
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z TRACE agent::util::discovery_operator::start_discovery] listen_for_new_discovery_handlers - received message to stop discovery for configuration Some("udev-keyboard")
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z TRACE agent::util::discovery_operator] stop_all_discovery - discovery client for udev discovery handler at endpoint Uds("/var/lib/akri/udev.sock") told to stop
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z TRACE agent::util::discovery_operator] internal_do_discover - received message to stop discovery for endpoint Uds("/var/lib/akri/udev.sock") serving protocol udev
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z TRACE agent::util::discovery_operator] internal_do_discover - received message to stop discovery for endpoint Uds("/var/lib/akri/udev.sock") serving protocol udev
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z TRACE agent::util::config_action] handle_config_delete - for config ("akri-discovered", "udev-keyboard") received message that do_periodic_discovery ended
[pod/akri-agent-daemonset-jb66t/akri-agent] [2023-05-04T12:40:30Z TRACE agent::util::config_action] handle_config_delete - found Instance udev-keyboard-4058be associated with deleted config ("akri-discovered", "udev-keyboard") ... sending message to end list_and_watch
...
```
Note the 2 lines of ` received message to stop discovery for endpoint `

### PR DESCRIPTION
**Pull request by diconico07**
**What this PR does / why we need it**:
The stop discovery channel is shared by all Configuration resources of a given discovery handler endpoint, this channel was used without giving any context of the targeted DiscoveryOperator, leading to a stop of discovery for all Configurations when a Configuration is modified or deleted.

This commit makes the stop discovery channel send the concerned Configuration ID (namespace + name) on the channel, allowing to filter out requests targeting another DiscoveryOperator, the channel is still shared so the cases where we really want to stop discovery for all Configurations still works.

Fixes #601 

**Special notes for your reviewer**:
Currently in draft as I still need to add some tests

**If applicable**:
- [ ] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [ ] this PR contains unit tests
- [x] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [x] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [x] inline documentation builds (`cargo doc`)
- [x] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

**Comment by kate-goldenring** [comment]
It's been awhile since I've looked at this, but aren't we creating a discovery operator for each configuration, regardless of whether they have a shared Discovery Handler / protocol? https://github.com/project-akri/akri/blob/54d5584cf523708609389e1bafd4536a1bd7e589/agent/src/util/config_action.rs#L256

**Comment by diconico07** [comment]
We indeed create a discovery operator per configuration, but the `stop_discovery_sender` you highlight here triggers a `stop_all_discovery` from the operator, that will iterate over the discovery handler's endpoints to tell each of them to stop discovery.
https://github.com/project-akri/akri/blob/54d5584cf523708609389e1bafd4536a1bd7e589/agent/src/util/discovery_operator.rs#L97-L98

This is needed as we do an `internal_do_discover` per handler's endpoint (eventually `do_discover_on_discovery_handler` calls it).
https://github.com/project-akri/akri/blob/54d5584cf523708609389e1bafd4536a1bd7e589/agent/src/util/discovery_operator.rs#L601-L616

And as the `discovery_handler_map` (and thus the `close_discovery_handler_connection`) is shared at agent level, we need to do it this way.
We could also have another broadcast channel at operator's level that is not shared between operators, but we would still need the shared one to correctly handle endpoint changes, so I found it easier this way.

File: agent/src/util/registration.rs [hunk 1]
```diff
@@ -126,7 +127,7 @@ impl Registration for AgentRegistration {
                     // 2) a connection cannot be made with the DH's endpoint
```
Comment (bfjelds) [inline agent/src/util/registration.rs:127]: maybe update comment to say what sending None does

File: agent/src/util/discovery_operator.rs [hunk 2]
```diff
@@ -95,7 +103,7 @@ impl DiscoveryOperator {
             discovery_handler_map.get_mut(&self.config.spec.discovery_handler.name)
         {
             for (endpoint, dh_details) in discovery_handler_details_map.clone() {
-                match dh_details.close_discovery_handler_connection.send(()) {
+                match dh_details.close_discovery_handler_connection.send(Some(self.get_config_id())) {
```
Comment (bfjelds) [inline agent/src/util/discovery_operator.rs:106]: add comment describing why we are sending configid

File: agent/src/util/discovery_operator.rs [hunk 3]
```diff
@@ -206,13 +214,25 @@ impl DiscoveryOperator {
...
-        let stop_discovery_receiver: &mut tokio::sync::broadcast::Receiver<()> =
+        let stop_discovery_receiver: &mut tokio::sync::broadcast::Receiver<Option<ConfigId>> =
             &mut dh_details.close_discovery_handler_connection.subscribe();
         loop {
             // Wait for either new discovery results or a message to stop discovery
             tokio::select! {
-                _ = stop_discovery_receiver.recv() => {
-                    trace!("internal_do_discover - received message to stop discovery for endpoint {:?} serving protocol {}", dh_details.endpoint, discovery_operator.get_config().spec.discovery_handler.name);
+                result = stop_discovery_receiver.recv() => {
+                    if let Ok(Some(config_id)) = result {
```
Comment (bfjelds) [inline agent/src/util/discovery_operator.rs:223]: add comment saying something like `stop is triggered iff None is sent (in which case, all are stopped) or if this config_id is sent (in which case, only this is stopped)`

File: agent/src/util/discovery_operator.rs [hunk 4]
```diff
@@ -206,13 +214,25 @@ impl DiscoveryOperator {
...
+                        if config_id != self.get_config_id() {
+                            trace!("internal_do_discover - received message to stop discovery for another configuration");
```
Comment (bfjelds) [inline agent/src/util/discovery_operator.rs:225]: in log message maybe mention that the stop message is ignored

File: agent/src/util/discovery_operator.rs [hunk 5]
```diff
@@ -689,11 +709,21 @@ pub mod start_discovery {
...
             }
 
-            if tokio::time::timeout(sleep_duration, stop_discovery_receiver.recv())
-                .await
-                .is_ok()
+            if let Ok(result) =
+                tokio::time::timeout(sleep_duration, stop_discovery_receiver.recv()).await
             {
-                trace!("do_discover_on_discovery_handler - received message to stop discovery for {} Discovery Handler at endpoint {:?}", dh_details.name, dh_details.endpoint);
+                if let Ok(Some(config_id)) = result {
```
Comment (bfjelds) [inline agent/src/util/discovery_operator.rs:715]: same request for a little comment describing how send(None) and send(configid) are handled here

**Comment by diconico07** [comment]
@bfjelds I added/modified the comments, please tell me if it better now

**Review by bfjelds — APPROVED** [review]
