### PR TITLE
Fix OPC Discovery Handler resolving IP bug

### LINKED ISSUE #583: OPC discovery handler duplicates the endpoint path
**Describe the bug**
This PR https://github.com/project-akri/akri/pull/570 fixes the issue when the OPC server returns a URL that is not resolvable by the broker/discovery handler by patching the IP address that user passes in. For example, user passes in `opc.tcp://192.168.0.1:50000`, and the server returns `opc.tcp://unresolvable-hostname:50000/OPCUA/Simulation`, then OPC Discovery Handler will pass in `opc.tcp://192.168.0.1:50000/OPCUA/Simulation` to the broker instead.

However, if the user also specifies the endpoint `opc.tcp://192.168.0.1:50000/OPCUA/Simulation`, then the OPC Discovery Handler will patch the URL to `opc.tcp://192.168.0.1:50000/OPCUA/Simulation/OPCUA/Simulation`.

**Output of `kubectl get pods,akrii,akric -o wide`**

**Kubernetes Version: [e.g. Native Kubernetes 1.19, MicroK8s 1.19, Minikube 1.19, K3s]**

**To Reproduce**
1. Create cluster using '...'
2. Install Akri with the Helm command '...'
3. '...'

**Expected behavior**

**Logs (please share snips of applicable logs)**
 - To get the logs of any pod, run `kubectl logs <pod name>`
 - To get the logs of a pod that has already terminated, `kubectl get logs <pod name> --previous`
 - If you believe that the problem is with the Kubelet, run `journalctl -u kubelet` or `journalctl -u snap.microk8s.daemon-kubelet` if you are using a MicroK8s cluster.

**Additional context**

### PR DESCRIPTION
**Pull request by harrison-tin**
**What this PR does / why we need it**:
fix the bug introduced from https://github.com/project-akri/akri/pull/570.
**Special notes for your reviewer**:
closes #583
**If applicable**:
- [ ] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [ ] this PR contains unit tests
- [ ] added code adheres to standard Rust formatting (`cargo fmt`)
- [ ] code builds properly (`cargo build`)
- [ ] code is free of common mistakes (`cargo clippy`)
- [ ] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [ ] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

File: discovery-handlers/opcua/src/discovery_impl.rs [hunk 1]
```diff
@@ -193,29 +193,39 @@ fn get_socket_addr(url: &str) -> Result<SocketAddr, anyhow::Error> {
...
-    let url = Url::parse(&discovery_url)
-        .map_err(|_| anyhow::format_err!("could not parse url {discovery_url}"))?;
-    if url.scheme() != OPC_TCP_SCHEME {
+fn get_discovery_url_ip(
+    ip_url_str: &str,
+    discovery_url_str: String,
+) -> Result<String, anyhow::Error> {
+    let ip_url = Url::parse(ip_url_str)
+        .map_err(|_| anyhow::format_err!("could not parse url {ip_url_str}"))?;
+    let discover_url = Url::parse(&discovery_url_str)
```
Comment (kate-goldenring) [inline discovery-handlers/opcua/src/discovery_impl.rs:202]: nit: `discovery_url`

File: discovery-handlers/opcua/src/discovery_impl.rs [hunk 2]
```diff
@@ -193,29 +193,39 @@ fn get_socket_addr(url: &str) -> Result<SocketAddr, anyhow::Error> {
...
+            if ip_url_str.ends_with('/') && path.starts_with('/') {
                 path.remove(0);
             }
-            let url = format!("{}{}", ip_url, path);
+            let url = if ip_url.path() == "" || ip_url.path() == "/" {
+                format!("{}{}", ip_url, path)
+            } else {
+                ip_url_str.to_string()
+            };
+            //let url = format!("{}{}", ip_url, path);
```
Comment (kate-goldenring) [inline discovery-handlers/opcua/src/discovery_impl.rs:228]: this comment looks like it can be cleaned up

File: discovery-handlers/opcua/src/discovery_impl.rs [hunk 3]
```diff
@@ -193,29 +193,39 @@ fn get_socket_addr(url: &str) -> Result<SocketAddr, anyhow::Error> {
...
-fn get_discovery_url_ip(ip_url: &str, discovery_url: String) -> Result<String, anyhow::Error> {
-    let url = Url::parse(&discovery_url)
-        .map_err(|_| anyhow::format_err!("could not parse url {discovery_url}"))?;
-    if url.scheme() != OPC_TCP_SCHEME {
+fn get_discovery_url_ip(
+    ip_url_str: &str,
+    discovery_url_str: String,
+) -> Result<String, anyhow::Error> {
+    let ip_url = Url::parse(ip_url_str)
+        .map_err(|_| anyhow::format_err!("could not parse url {ip_url_str}"))?;
```
Comment (kate-goldenring) [inline discovery-handlers/opcua/src/discovery_impl.rs:201]: Mapping errors can be simplified by importing `anyhow::Error` and doing the following
```suggestion
        .with_context(|_| "could not parse url {ip_url_str}")?;
```

**Review by kate-goldenring — COMMENTED** [review]
A couple clean up nits

**Comment by harrison-tin** [comment]
> A couple clean up nits

File: discovery-handlers/opcua/src/discovery_impl.rs (hunk 1 above)
Comment (harrison-tin) [reply discovery-handlers/opcua/src/discovery_impl.rs]: thanks, updated to address feedback

**Comment by harrison-tin** [comment]
> A couple clean up nits

@kate-goldenring thanks, updated to address feedback

**Review by kate-goldenring — APPROVED** [review]
